version: "3.2"
services:
  hpts:
    image: hatmatrix/ds4b_highperfts:latest
    ports:
      - "8787:8787"
      - "3838:3838"
    environment:
      DISABLE_AUTH: "true"
    volumes:
      - type: "bind"
        source: "$HOME/github"
        target: "/home/rstudio"